version: '3.8'
services:
  mysql:
    image: mysql:8
    hostname: metacourses
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=metacourses
      - MYSQL_USER=metacoders
      - MYSQL_PASSWORD=metacoders123
    ports:
      - 3306:3306
    networks:
      - metanet
    restart: on-failure

  web:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/metacoders-courses-service
    command: sh -c "npx prisma db push && npm run dev"
    depends_on:
      - mysql
    ports:
      - 3002:3001
    networks:
      - metanet
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://blogmeta_meta:1q2w3e@box2007.bluehost.com:3306/blogmeta_metacourses ## mysql://root:KexqxElCEK9nclyxDG20@containers-us-west-66.railway.app:6692/railway ## mysql://metacoders:metacoders123@mysql:3306/metacourses
    restart: on-failure

networks:
  metanet:
    driver: bridge

    