#docker-compose -f docker-compose.yml -p puppeteer_mysql up --build
version: '3.8'
services:
  puppeteer_workspace:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/code_puppeteer
    command: sh -c "npm run start"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://blogmeta_meta:1q2w3e@box2007.bluehost.com:3306/blogmeta_metacourses ## mysql://root:KexqxElCEK9nclyxDG20@containers-us-west-66.railway.app:6692/railway ## mysql://metacoders:metacoders123@mysql:3306/metacourses
    restart: on-failure



    