# fly.toml file generated for mysqlmetacourses on 2022-09-05T10:53:48+07:00

app = "mysqlmetacourses"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  MYSQL_DATABASE = "metacourses"
  MYSQL_USER = "root"

[mounts]
  destination = "/data"
  source = "mysql_data"

[[services]]
  internal_port = 3306
[build]
  image = "mysql:5.6"

[experimental]
  cmd = [
    "--default-authentication-plugin", 
    "mysql_native_password", 
    "--datadir", 
    "/data/mysql"
  ]